/**
 * Schema Types for Dynamic Multi-Tenant Schemas
 *
 * Phase 2: Schema Infrastructure
 *
 * These types define the structure for customer-defined authorization schemas.
 * Each organization can define custom entity types and relationships.
 */

export interface CompiledSchema {
  version: number;
  entities: EntityDefinition[];
  relationships: RelationshipDefinition[];
  indexes: IndexDefinition[];
}

export interface EntityDefinition {
  name: string;
  fields: FieldDefinition[];
  createTableSQL: string; // Generated by compiler
}

export interface RelationshipDefinition {
  name: string;
  from: string;
  to: string;
  properties: FieldDefinition[];
  createRelTableSQL: string; // Generated by compiler
}

export interface FieldDefinition {
  name: string;
  type: "STRING" | "NUMBER" | "BOOLEAN" | "REFERENCE";
  primaryKey?: boolean;
  required?: boolean;
  unique?: boolean;
}

export interface IndexDefinition {
  entity: string;
  field: string;
  createIndexSQL: string; // Generated by compiler
}

/**
 * Default schema for new organizations
 * Matches Phase 1 hardcoded schema
 */
export function getDefaultSchema(): CompiledSchema {
  return {
    version: 1,
    entities: [
      {
        name: "User",
        fields: [
          { name: "id", type: "STRING", primaryKey: true, required: true },
        ],
        createTableSQL: "CREATE NODE TABLE User(id STRING, PRIMARY KEY(id))",
      },
      {
        name: "Group",
        fields: [
          { name: "id", type: "STRING", primaryKey: true, required: true },
        ],
        createTableSQL: "CREATE NODE TABLE Group(id STRING, PRIMARY KEY(id))",
      },
      {
        name: "Resource",
        fields: [
          { name: "id", type: "STRING", primaryKey: true, required: true },
        ],
        createTableSQL:
          "CREATE NODE TABLE Resource(id STRING, PRIMARY KEY(id))",
      },
    ],
    relationships: [
      {
        name: "member_of",
        from: "User",
        to: "Group",
        properties: [],
        createRelTableSQL: "CREATE REL TABLE member_of(FROM User TO Group)",
      },
      {
        name: "inherits_from",
        from: "Group",
        to: "Group",
        properties: [],
        createRelTableSQL:
          "CREATE REL TABLE inherits_from(FROM Group TO Group)",
      },
      {
        name: "has_permission",
        from: "User",
        to: "Resource",
        properties: [{ name: "permission", type: "STRING", required: true }],
        createRelTableSQL:
          "CREATE REL TABLE has_permission(FROM User TO Resource, permission STRING)",
      },
      {
        name: "group_permission",
        from: "Group",
        to: "Resource",
        properties: [{ name: "permission", type: "STRING", required: true }],
        createRelTableSQL:
          "CREATE REL TABLE group_permission(FROM Group TO Resource, permission STRING)",
      },
    ],
    indexes: [],
  };
}
